version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      - SECRET_KEY=mysecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: